### PR TITLE
Add 404 page

### PR DESCRIPTION
**Pull request by dotangad**
This is what it looks like -
screenshot

Here's the changed route, let me know if I've done anything wrong - 
```js
/**
 * Redirect actual shortlinks.
 */
router.get('*', async ctx => {
  const { pathname } = ctx.URL
  if (pathname === '/') {
    ctx.redirect('https://exunclan.com')
    return
  }
  const shortlink = await Shortlink.query().findOne('slug', pathname.slice(1))
  if (!shortlink) {
    await ctx.render('404')
    ctx.status = 404
    return
  }
  ctx.redirect(shortlink.target)
})
```

### CODE REVIEW

**Comment by kbrgl** [comment]
Thanks for the PR, Angad. Could you use ctx.throw(404) instead? More idiomatic for Koa. Do the error handling in `app.js`.

If you’d like me to merge this in anyway, that’s fine too. It is after all a `*` route, and I don’t expect that we’ll add any other routes. Just saying because this code won’t render the prettier 404 if you add another route that throws 404.

**Review by kbrgl — CHANGES_REQUESTED** [review]
**To do:** Revert the `*` route to ctx.throw(404).

For error handling, there’s a `try-catch` middleware in `app.js`. Move the new code in the `*` route to the catch block, and change the 404 page to a generic error page that requires a status code and status for rendering. This way any error that is thrown in any route will result in a pretty error page.

**Comment by dotangad** [comment]
@kbrgl Fixed

**Comment by kbrgl** [comment]
Not exactly what I requested, but this works as well! Thanks, LGTM!

**Comment by kbrgl** [comment]
Oh wait, one last thing before I merge. Have you tested this on your machine?

**Comment by dotangad** [comment]
@kbrgl Yes, I've tested this on my machine. If you want I can change this to a generic error page?

**Comment by kbrgl** [comment]
Don’t, this is fine.

**Pull request merged**
